# Generated by Django 3.2.14 on 2022-11-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='login_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='taskapp.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='taskapp.login'),
            preserve_default=False,
        ),
    ]
