# Generated by Django 3.2.14 on 2022-11-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20221118_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('mark', models.DateField()),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.student')),
            ],
        ),
    ]
