# Generated by Django 3.2.14 on 2022-11-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(max_length=100),
        ),
    ]
